# Generated by Django 3.2 on 2021-06-04 21:27

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('martorfield', martor.models.MartorField(blank=True, null=True)),
            ],
        ),
    ]
